#!/bin/bash -l

# ==== ONLY EDIT WITHIN THIS BLOCK =====

export SWARM_CUSTOMER_ENV="py_data_science"
if ! [[ -z "${SWARM_CUSTOMER_SCRATCH_PREFIX}" ]] && ! [[ -z "${JUPYTERHUB_USER}" ]]; then
    export SWARM_CUSTOMER_SCRATCH="${SWARM_CUSTOMER_SCRATCH_PREFIX}/${JUPYTERHUB_USER}/"
fi

# ==== ONLY EDIT WITHIN THIS BLOCK =====

exec "$@"